### ISSUE TITLE
Can you tell me how your project environment is configured？

### ISSUE THREAD

**Issue by zzhujiuxingc** [jrainey12/gait-transformer#2]
Hello, Thank you for your great idea and work.
Can you tell me how your project environment is configured？Please tell me how to use your project code if you can.
And are you the author of the paper 《Gait-ViT: Gait Recognition with Vision Transformer》？
Thank you for your help.

**Comment by zzhujiuxingc** [comment]
Sorry to interrupt. I encountered a problem when training the model, using the casia-b dataset for training reported an error:

/opt/conda/conda-bld/pytorch_1639180543123/work/aten/src/ATen/native/cuda/Loss.cu:247: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1639180543123/work/aten/src/ATen/native/cuda/Loss.cu:247: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/home/xiaopeng/pythonProject/gait-transformer/train_test_ViT.py", line 85, in <module>
    main(args.input_dir, args.input_type, args.mode, args.model_name, args.lr, args.bs, args.epochs)
  File "/home/xiaopeng/pythonProject/gait-transformer/train_test_ViT.py", line 23, in main
    GEI(input_dir, lr, bs, epochs, mode, model_name)
  File "/home/xiaopeng/pythonProject/gait-transformer/GEI/Gender_ViT_GEI.py", line 121, in main
    t_loss, t_acc = train(model, optimizer, train_dataloader, epoch + 1, batch_size, use_gpu)  # , writer)
  File "/home/xiaopeng/pythonProject/gait-transformer/GEI/Gender_ViT_GEI.py", line 428, in train
    loss = loss_fn(y_pred, torch.max(y.view(x.size(0), -1).long(), 1)[0])
  File "/home/xiaopeng/anaconda3/envs/gait-vit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaopeng/anaconda3/envs/gait-vit/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 1152, in forward
    label_smoothing=self.label_smoothing)
  File "/home/xiaopeng/anaconda3/envs/gait-vit/lib/python3.7/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: device-side assert triggered

Process finished with exit code 1

And how to set up the training set and validation set is not written in the code. I would be very grateful if you could help me slove the questions！

**Comment by james-rainey** [comment]
Hi,
I am not the author of that paper.
This is just a side project that I worked on and haven't completed yet.
The environment I used is just a standard pytorch conda environment, nothing extra.

The error you encountered looks to be an issue with the number of classes. This method is set up as a binary classifier and would require modification to work with multi-class data.

The code is set up to work for gender classification only and requires the dataset to be split and labelled by gender. There is a sampling script in the utils folder to help with this.
The training data is set up with two folders, gallery and probe, and a text file with labels. Each line of the text file has the format: "image_name  class_id"  where image_name is the path to each image and class_id is 0 or 1 for male or female.

Hope that helps.
